# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='群名')),
            ],
        ),
        migrations.CreateModel(
            name='QAKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, verbose_name='关键字')),
            ],
        ),
        migrations.CreateModel(
            name='QAReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.CharField(blank=True, max_length=30, null=True, verbose_name='描述')),
                ('is_pic', models.BooleanField(default=False, verbose_name='是否图片')),
                ('reply_text', models.TextField(blank=True, null=True, verbose_name='回答')),
                ('reply_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片回答')),
                ('keywords', models.ManyToManyField(related_name='replies', to='webotconf.QAKeyWord', verbose_name='关键字集')),
            ],
        ),
        migrations.CreateModel(
            name='RuleAddFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, verbose_name='关键字')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webotconf.ChatRoom', verbose_name='群')),
            ],
        ),
    ]
