# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webotconf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='order',
            field=models.IntegerField(default=1, unique=True, verbose_name='优先级'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruleaddfriend',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='webotconf.ChatRoom', verbose_name='群'),
        ),
    ]
