# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webotconf', '0003_qakeyword_is_strict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qareply',
            old_name='disc',
            new_name='desc',
        ),
    ]
