# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labcrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='labcrm.LabUser', verbose_name='用户'),
        ),
    ]
