# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labcrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog', models.TextField(verbose_name='对话记录')),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labcrm.LabUser', verbose_name='用户')),
            ],
        ),
    ]
