# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcrm', '0002_auto_20170622_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattr',
            name='options',
            field=models.TextField(blank=True, null=True, verbose_name='选项'),
        ),
    ]
