# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcrm', '0002_auto_20170721_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpic',
            old_name='upic',
            new_name='pic',
        ),
        migrations.AlterField(
            model_name='userpic',
            name='pic_type',
            field=models.CharField(default='NoType', max_length=30, verbose_name='图片类型'),
        ),
    ]
