# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labcrm', '0002_dialog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaPerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='秘钥')),
                ('data', models.TextField(verbose_name='问卷页面')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='is_fill',
            field=models.BooleanField(default=False, verbose_name='是否填写'),
        ),
        migrations.AddField(
            model_name='paperdata',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='labcrm.Paper', verbose_name='问卷'),
        ),
    ]
